language: csharp
mono: 4.6.1
sudo: false

cache:
  directories:
  - engine/thirdparty/download

addons:
  apt:
    packages:
    - lua5.1

script:
  - ./setup.sh
  - travis_retry ./rebuild.sh

notifications:
 
before_deploy:
  - "./package.sh ${TRAVIS_TAG} ${PWD}/build/"

deploy:
  provider: releases
  api_key:
    secure: FLNsFVaq/8z40bbpYbKO7uD+3SRNV98He0iGlX0oT0bzN6Y1DvSnlxuQvG1R36wFCTbJlPJlFTVkp+bQgE0F4qrZI7QRvYL/r2ffMfZwPYGDMnh6dlmWF14Z8OPgg9SSRDBsorRglvztiwIgueeV3jSG/7lVUkuadQP7x24fF1JWYTAEpe1WOTiYeByYsSiMpJQijnsWx5l2TeN3zeTRQ85ETHJ1VsEWz6haqOugGm2WH3gHqJH9BKsf5v1Zz8K2irqsDenS18Ymm8BL77vLvKX0a+5VvWpoVKevjz3mj9I0T0fPkwlGPien9B6ueBp7wM/0DL4lrAjgKVHxjQeyNHFez/APyJGSPezi+a4s4DzyEWKfP09o+u7+dL1tEOVaaGRL3PadoUHhv0wQ9HAyr7jQGDhG07bN+swpIB1MCoBAK0wRhlJhTGWkxm4YSD4BHX5BCI7SJ+QcSOWl36EJS/dc+Y9BBxmo98aqFztqUtpPJqzUNXsze7PyKJ9J7rCBGAn6w8X/u/M6a4TXN58STJv/JQdELofJJ2OFv/0FN/qQ3KDgLvB+xi16roUHzmhX4qVTRdUJDXpXQ8qBeqdsidI73Rk/2Aol6GlYuUOb+rOmmDhmqozm7qrX9aUCbAIHsAdm7MzbmvZ/+EsotK0/sTVkYdWXiU6qYiyLqTeMhVU=
  file:
    - build/RA2A-{TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: RA2A/RA2A
